package testng.parallelExecution;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.aventstack.extentreports.reporter.JsonFormatter;

public class MergeReport {

	public static void main(String [] args)
	{
		  //Creating a Directory for Extent Json Output and create it if doesn't exist
        File file = new File("ExtentJson");
        if (!file.exists()) {
            file.mkdir();
        }
        String opFolder = file.getPath();

        //Creating individual Report Number 1
        ExtentSparkReporter spark = new ExtentSparkReporter("Report1.html");
        JsonFormatter json = new JsonFormatter(opFolder + "/Report1.json");
        ExtentReports extent = new ExtentReports();
        extent.createTest("test1").assignCategory("cat").pass("Step 1 from test 1")
            .fail("step 2 from test 1");
        extent.attachReporter(spark);
        
//        ExtentReports extent3 = new ExtentReports();
//        extent.createTest("test3").assignCategory("cat").pass("Step 1 from test 3");
          
        extent.attachReporter(spark);
       // extent.attachReporter(json, spark);
        extent.flush();

        //Creating individual Report Number 2
        ExtentSparkReporter spark2 = new ExtentSparkReporter("Report2.html");
        JsonFormatter json2 = new JsonFormatter(opFolder + "/Report2.json");
        ExtentReports extent2 = new ExtentReports();
        extent2.createTest("test1").assignCategory("cat").pass("Step 1 from test 2")
            .fail("step 2 from test 2");
        extent2.attachReporter(spark2);
       // extent2.attachReporter(json2, spark2);
        extent2.flush();
        
        
        
        ExtentSparkReporter mergedSpark = new ExtentSparkReporter("merge.html");
        ExtentReports extentMerged = new ExtentReports();

        //Replace below logic to get all the .json files generated by extent in opFolder
        File jsonOPDirectory = new File("ExtentJson");
        if (jsonOPDirectory.exists()) {
            Arrays.stream(jsonOPDirectory.listFiles()).forEach(jsonFile -> {

                try {
                    extentMerged.createDomainFromJsonArchive(jsonFile.getPath());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });
        }

        extentMerged.attachReporter(mergedSpark);
        extentMerged.flush();
	}
	
}
